global_options:
  dart_mappable_builder:
    options:
      caseStyle: camelCase
      enumCaseStyle: camelCase
      ignoreNull: true
      discriminatorKey: type


targets:
  $default:
    builders:
      dart_mappable_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart':
              - 'lib/{{path}}/generated/{{file}}.mapper.dart'
              - 'lib/{{path}}/generated/{{file}}.init.dart'