name: pub_dev_browser_lib
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_highlighter: ^0.1.1
  flutter_markdown: ^0.7.3+2
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  fuzzywuzzy: ^1.2.0
  github: ^9.24.0
  go_router: ^14.2.7
  hydrated_bloc: ^9.1.5
  logger: ^2.4.0
  markdown: ^7.2.2
  meta: ^1.15.0
  path_provider: ^2.1.4
  pub_api_client: ^3.0.0
  pubspec: ^2.3.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  dart_mappable_builder: ^4.2.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
